In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2])

In [3]:
a

array([0, 1, 2])

In [4]:
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [5]:
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [6]:
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [7]:
b = np.array([[1, 2], [3, 4]])

In [8]:
b

array([[1, 2],
       [3, 4]])

In [9]:
np.tile(b, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [10]:
np.tile(b, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [11]:
c = np.array([1,2,3,4])

In [12]:
c

array([1, 2, 3, 4])

In [13]:
np.tile(c,(4,1))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])